version: "3.3"

services:
  postgres:
    image: postgis/postgis:14-master
    networks:
      - internal
    ports:
      - 5112:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smalsuolis
      TZ: 'Etc/GMT'
      PGTZ: 'Etc/GMT'

  chrome:
    image: browserless/chrome:latest
    restart: unless-stopped
    platform: linux/amd64
    environment:
      DEFAULT_LAUNCH_ARGS: '["--window-size=1920,1080"]'
      WORKSPACE_DELETE_EXPIRED: true
      MAX_CONCURRENT_SESSIONS: 10
      MAX_QUEUE_LENGTH: 10
      CONNECTION_TIMEOUT:  3600000
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://127.0.0.1:3000/metrics || exit 1" ]
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    ports:
      - 9321:3000

  redis:
    image: redis:latest
    networks:
      - internal
    ports:
      - 6112:6379

networks:
  internal:

volumes:
  data:
