
version: "3.3"

services:
  postgres:
    image: postgis/postgis:14-master
    networks:
      - internal
    ports:
      - 5112:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smalsuolis
      TZ: 'Etc/GMT'
      PGTZ: 'Etc/GMT'

  redis:
    image: redis:latest
    networks:
      - internal
    ports:
      - 6112:6379

networks:
  internal:

volumes:
  data: