// This file is auto-generated by @hey-api/openapi-ts

export const AddressSchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the address',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the address',
    },
    plot_or_building_number: {
      type: 'string',
      title: 'Plot Or Building Number',
      description: 'Plot or building number of the address',
    },
    building_block_number: {
      anyOf: [
        {
          type: 'string',
          minLength: 1,
        },
        {
          type: 'null',
        },
      ],
      title: 'Building Block Number',
      description: 'Plot or building number of the address',
    },
    postal_code: {
      type: 'string',
      title: 'Postal Code',
      description: 'Postal code of the address',
    },
    street: {
      anyOf: [
        {
          $ref: '#/components/schemas/FlatStreet',
        },
        {
          type: 'null',
        },
      ],
      description: 'Street information the address belongs to',
    },
    residential_area: {
      anyOf: [
        {
          $ref: '#/components/schemas/FlatResidentialArea',
        },
        {
          type: 'null',
        },
      ],
      description: 'Residential area information the address belongs to',
    },
    municipality: {
      $ref: '#/components/schemas/ShortMunicipality',
      description: 'Municipality information the address belongs to',
    },
    geometry: {
      $ref: '#/components/schemas/Geometry',
      description: 'Point geometry of the address',
    },
  },
  type: 'object',
  required: [
    'code',
    'feature_id',
    'plot_or_building_number',
    'building_block_number',
    'postal_code',
    'street',
    'residential_area',
    'municipality',
    'geometry',
  ],
  title: 'Address',
} as const;

export const AddressSearchSortBySchema = {
  type: 'string',
  enum: [
    'code',
    'plot_or_building_number',
    'building_block_number',
    'postal_code',
    'feature_id',
    'created_at',
  ],
  title: 'AddressSearchSortBy',
} as const;

export const AddressesFilterSchema = {
  properties: {
    codes: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Codes',
      description: 'Filter by codes',
      examples: [[]],
    },
    feature_ids: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Feature Ids',
      description: 'Filter by feature IDs',
      examples: [[]],
    },
    plot_or_building_number: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by plot or building number',
    },
    building_block_number: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by building block number',
    },
    postal_code: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by postal code',
    },
  },
  type: 'object',
  title: 'AddressesFilter',
} as const;

export const AddressesSearchFilterRequestSchema = {
  properties: {
    geometry: {
      anyOf: [
        {
          $ref: '#/components/schemas/GeometryFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by geometry',
    },
    counties: {
      anyOf: [
        {
          $ref: '#/components/schemas/CountiesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by counties',
    },
    municipalities: {
      anyOf: [
        {
          $ref: '#/components/schemas/MunicipalitiesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by municipalities',
    },
    residential_areas: {
      anyOf: [
        {
          $ref: '#/components/schemas/ResidentialAreasFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by residential areas',
    },
    streets: {
      anyOf: [
        {
          $ref: '#/components/schemas/StreetsFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by streets',
    },
    addresses: {
      anyOf: [
        {
          $ref: '#/components/schemas/AddressesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by addresses',
    },
  },
  type: 'object',
  title: 'AddressesSearchFilterRequest',
} as const;

export const AddressesSearchRequestSchema = {
  properties: {
    filters: {
      items: {
        $ref: '#/components/schemas/AddressesSearchFilterRequest',
      },
      type: 'array',
      title: 'Filters',
      description: 'A list of filters to apply for searching addresses, combined using OR logic.',
      default: [],
    },
  },
  type: 'object',
  title: 'AddressesSearchRequest',
} as const;

export const CountiesFilterSchema = {
  properties: {
    codes: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Codes',
      description: 'Filter by codes',
      examples: [[]],
    },
    feature_ids: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Feature Ids',
      description: 'Filter by feature IDs',
      examples: [[]],
    },
    name: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by name',
    },
  },
  type: 'object',
  title: 'CountiesFilter',
} as const;

export const CountiesSearchFilterRequestSchema = {
  properties: {
    geometry: {
      anyOf: [
        {
          $ref: '#/components/schemas/GeometryFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by geometry',
    },
    counties: {
      anyOf: [
        {
          $ref: '#/components/schemas/CountiesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by counties',
    },
  },
  type: 'object',
  title: 'CountiesSearchFilterRequest',
} as const;

export const CountiesSearchRequestSchema = {
  properties: {
    filters: {
      items: {
        $ref: '#/components/schemas/CountiesSearchFilterRequest',
      },
      type: 'array',
      title: 'Filters',
      description: 'A list of filters to apply for searching counties, combined using OR logic.',
      default: [],
    },
  },
  type: 'object',
  title: 'CountiesSearchRequest',
} as const;

export const CountySchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the county',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the county',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Name of the county',
    },
    area_ha: {
      type: 'number',
      title: 'Area Ha',
      description: 'Area of the county in hectares',
    },
    created_at: {
      type: 'string',
      format: 'date',
      title: 'Created At',
      description: 'Date of creation of the county',
    },
  },
  type: 'object',
  required: ['code', 'feature_id', 'name', 'area_ha', 'created_at'],
  title: 'County',
} as const;

export const CountyWithGeometrySchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the county',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the county',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Name of the county',
    },
    area_ha: {
      type: 'number',
      title: 'Area Ha',
      description: 'Area of the county in hectares',
    },
    created_at: {
      type: 'string',
      format: 'date',
      title: 'Created At',
      description: 'Date of creation of the county',
    },
    geometry: {
      $ref: '#/components/schemas/Geometry',
      description: 'Geometry information of the county',
    },
  },
  type: 'object',
  required: ['code', 'feature_id', 'name', 'area_ha', 'created_at', 'geometry'],
  title: 'CountyWithGeometry',
} as const;

export const CursorPage_Address_Schema = {
  properties: {
    items: {
      items: {
        $ref: '#/components/schemas/Address',
      },
      type: 'array',
      title: 'Items',
    },
    total: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Total',
      description: 'Total items',
    },
    current_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Page',
      description: 'Cursor to refetch the current page',
    },
    current_page_backwards: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Page Backwards',
      description: 'Cursor to refetch the current page starting from the last item',
    },
    previous_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Previous Page',
      description: 'Cursor for the previous page',
    },
    next_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Next Page',
      description: 'Cursor for the next page',
    },
  },
  type: 'object',
  required: ['items'],
  title: 'CursorPage[Address]',
} as const;

export const CursorPage_County_Schema = {
  properties: {
    items: {
      items: {
        $ref: '#/components/schemas/County',
      },
      type: 'array',
      title: 'Items',
    },
    total: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Total',
      description: 'Total items',
    },
    current_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Page',
      description: 'Cursor to refetch the current page',
    },
    current_page_backwards: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Page Backwards',
      description: 'Cursor to refetch the current page starting from the last item',
    },
    previous_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Previous Page',
      description: 'Cursor for the previous page',
    },
    next_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Next Page',
      description: 'Cursor for the next page',
    },
  },
  type: 'object',
  required: ['items'],
  title: 'CursorPage[County]',
} as const;

export const CursorPage_Eldership_Schema = {
  properties: {
    items: {
      items: {
        $ref: '#/components/schemas/Eldership',
      },
      type: 'array',
      title: 'Items',
    },
    total: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Total',
      description: 'Total items',
    },
    current_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Page',
      description: 'Cursor to refetch the current page',
    },
    current_page_backwards: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Page Backwards',
      description: 'Cursor to refetch the current page starting from the last item',
    },
    previous_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Previous Page',
      description: 'Cursor for the previous page',
    },
    next_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Next Page',
      description: 'Cursor for the next page',
    },
  },
  type: 'object',
  required: ['items'],
  title: 'CursorPage[Eldership]',
} as const;

export const CursorPage_Municipality_Schema = {
  properties: {
    items: {
      items: {
        $ref: '#/components/schemas/Municipality',
      },
      type: 'array',
      title: 'Items',
    },
    total: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Total',
      description: 'Total items',
    },
    current_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Page',
      description: 'Cursor to refetch the current page',
    },
    current_page_backwards: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Page Backwards',
      description: 'Cursor to refetch the current page starting from the last item',
    },
    previous_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Previous Page',
      description: 'Cursor for the previous page',
    },
    next_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Next Page',
      description: 'Cursor for the next page',
    },
  },
  type: 'object',
  required: ['items'],
  title: 'CursorPage[Municipality]',
} as const;

export const CursorPage_Parcel_Schema = {
  properties: {
    items: {
      items: {
        $ref: '#/components/schemas/Parcel',
      },
      type: 'array',
      title: 'Items',
    },
    total: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Total',
      description: 'Total items',
    },
    current_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Page',
      description: 'Cursor to refetch the current page',
    },
    current_page_backwards: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Page Backwards',
      description: 'Cursor to refetch the current page starting from the last item',
    },
    previous_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Previous Page',
      description: 'Cursor for the previous page',
    },
    next_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Next Page',
      description: 'Cursor for the next page',
    },
  },
  type: 'object',
  required: ['items'],
  title: 'CursorPage[Parcel]',
} as const;

export const CursorPage_ResidentialArea_Schema = {
  properties: {
    items: {
      items: {
        $ref: '#/components/schemas/ResidentialArea',
      },
      type: 'array',
      title: 'Items',
    },
    total: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Total',
      description: 'Total items',
    },
    current_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Page',
      description: 'Cursor to refetch the current page',
    },
    current_page_backwards: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Page Backwards',
      description: 'Cursor to refetch the current page starting from the last item',
    },
    previous_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Previous Page',
      description: 'Cursor for the previous page',
    },
    next_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Next Page',
      description: 'Cursor for the next page',
    },
  },
  type: 'object',
  required: ['items'],
  title: 'CursorPage[ResidentialArea]',
} as const;

export const CursorPage_Room_Schema = {
  properties: {
    items: {
      items: {
        $ref: '#/components/schemas/Room',
      },
      type: 'array',
      title: 'Items',
    },
    total: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Total',
      description: 'Total items',
    },
    current_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Page',
      description: 'Cursor to refetch the current page',
    },
    current_page_backwards: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Page Backwards',
      description: 'Cursor to refetch the current page starting from the last item',
    },
    previous_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Previous Page',
      description: 'Cursor for the previous page',
    },
    next_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Next Page',
      description: 'Cursor for the next page',
    },
  },
  type: 'object',
  required: ['items'],
  title: 'CursorPage[Room]',
} as const;

export const CursorPage_Street_Schema = {
  properties: {
    items: {
      items: {
        $ref: '#/components/schemas/Street',
      },
      type: 'array',
      title: 'Items',
    },
    total: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Total',
      description: 'Total items',
    },
    current_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Page',
      description: 'Cursor to refetch the current page',
    },
    current_page_backwards: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Page Backwards',
      description: 'Cursor to refetch the current page starting from the last item',
    },
    previous_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Previous Page',
      description: 'Cursor for the previous page',
    },
    next_page: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Next Page',
      description: 'Cursor for the next page',
    },
  },
  type: 'object',
  required: ['items'],
  title: 'CursorPage[Street]',
} as const;

export const EldershipSchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the eldership',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Name of the eldership',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the eldership',
    },
    area_ha: {
      type: 'number',
      title: 'Area Ha',
      description: 'Area of the eldership in hectares',
    },
    municipality: {
      $ref: '#/components/schemas/ShortMunicipality',
      description: 'Municipality information the eldership belongs to',
    },
    created_at: {
      type: 'string',
      format: 'date',
      title: 'Created At',
      description: 'Date of creation of the eldership',
    },
  },
  type: 'object',
  required: ['code', 'name', 'feature_id', 'area_ha', 'municipality', 'created_at'],
  title: 'Eldership',
} as const;

export const EldershipWithGeometrySchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the eldership',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Name of the eldership',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the eldership',
    },
    area_ha: {
      type: 'number',
      title: 'Area Ha',
      description: 'Area of the eldership in hectares',
    },
    municipality: {
      $ref: '#/components/schemas/ShortMunicipality',
      description: 'Municipality information the eldership belongs to',
    },
    created_at: {
      type: 'string',
      format: 'date',
      title: 'Created At',
      description: 'Date of creation of the eldership',
    },
    geometry: {
      $ref: '#/components/schemas/Geometry',
      description: 'Geometry information of the eldership',
    },
  },
  type: 'object',
  required: ['code', 'name', 'feature_id', 'area_ha', 'municipality', 'created_at', 'geometry'],
  title: 'EldershipWithGeometry',
} as const;

export const EldershipsFilterSchema = {
  properties: {
    codes: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Codes',
      description: 'Filter by codes',
      examples: [[]],
    },
    feature_ids: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Feature Ids',
      description: 'Filter by feature IDs',
      examples: [[]],
    },
    name: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by name',
    },
  },
  type: 'object',
  title: 'EldershipsFilter',
} as const;

export const EldershipsSearchFilterRequestSchema = {
  properties: {
    geometry: {
      anyOf: [
        {
          $ref: '#/components/schemas/GeometryFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by geometry',
    },
    counties: {
      anyOf: [
        {
          $ref: '#/components/schemas/CountiesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by counties',
    },
    municipalities: {
      anyOf: [
        {
          $ref: '#/components/schemas/MunicipalitiesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by municipalities',
    },
    elderships: {
      anyOf: [
        {
          $ref: '#/components/schemas/EldershipsFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by elderships',
    },
  },
  type: 'object',
  title: 'EldershipsSearchFilterRequest',
} as const;

export const EldershipsSearchRequestSchema = {
  properties: {
    filters: {
      items: {
        $ref: '#/components/schemas/EldershipsSearchFilterRequest',
      },
      type: 'array',
      title: 'Filters',
      description: 'A list of filters to apply for searching elderships, combined using OR logic.',
      default: [],
    },
  },
  type: 'object',
  title: 'EldershipsSearchRequest',
} as const;

export const FlatResidentialAreaSchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the residential area',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the residential area',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Name of the residential area',
    },
  },
  type: 'object',
  required: ['code', 'feature_id', 'name'],
  title: 'FlatResidentialArea',
} as const;

export const FlatStreetSchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the street',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the street',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Name of the street',
    },
    full_name: {
      type: 'string',
      title: 'Full Name',
      description: 'The full name of the street, including its type',
    },
  },
  type: 'object',
  required: ['code', 'feature_id', 'name', 'full_name'],
  title: 'FlatStreet',
} as const;

export const GeometrySchema = {
  properties: {
    srid: {
      type: 'integer',
      title: 'Srid',
      description: 'Spatial Reference Identifier (SRID) for the geometry',
    },
    data: {
      type: 'string',
      title: 'Data',
      description: 'Geometry data in WKB (Well-Known Binary) format, represented as a hex string',
    },
  },
  type: 'object',
  required: ['srid', 'data'],
  title: 'Geometry',
} as const;

export const GeometryFilterSchema = {
  properties: {
    method: {
      $ref: '#/components/schemas/GeometryFilterMethod',
      description: `Defines method used for filtering geometries:
- **\`intersects\`**: filter geometries that intersects any portion of space with the specified geometry.
- **\`contains\`**: filter geometries that are completely within the specified geometry.`,
      default: 'intersects',
    },
    ewkb: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Ewkb',
      description:
        'Extended Well-Known Binary (EWKB) represented as a hex string for geometry filtering',
      examples: [
        '0103000020E6100000010000000500000045F6419605473940B1DD3D40F7574B4045F641960547394061E124CD1F574B40719010E50B4A394061E124CD1F574B40719010E50B4A3940B1DD3D40F7574B4045F6419605473940B1DD3D40F7574B40',
      ],
    },
    ewkt: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Ewkt',
      description: 'Extended Well-Known Text (EWKT) for geometry filtering',
      examples: [
        'SRID=4326;POLYGON((25.277429 54.687233, 25.277429 54.680658, 25.289244 54.680658, 25.289244 54.687233, 25.277429 54.687233))',
      ],
    },
    geojson: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Geojson',
      description: 'GeoJson for geometry filtering',
      examples: [
        '{"crs":{"type":"name","properties":{"name":"EPSG:4326"}},"type":"Polygon","coordinates":[[[25.277429,54.687233],[25.277429,54.680658],[25.289244,54.680658],[25.289244,54.687233],[25.277429,54.687233]]]}',
      ],
    },
  },
  type: 'object',
  title: 'GeometryFilter',
} as const;

export const GeometryFilterMethodSchema = {
  type: 'string',
  enum: ['intersects', 'contains'],
  title: 'GeometryFilterMethod',
} as const;

export const GeometryOutputFormatSchema = {
  type: 'string',
  enum: ['ewkt', 'ewkb'],
  title: 'GeometryOutputFormat',
} as const;

export const HTTPExceptionResponseSchema = {
  properties: {
    detail: {
      type: 'string',
      title: 'Detail',
      description: 'Detailed error message',
    },
  },
  type: 'object',
  required: ['detail'],
  title: 'HTTPExceptionResponse',
  example: {
    detail: 'HTTPException raised.',
  },
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError',
      },
      type: 'array',
      title: 'Detail',
    },
  },
  type: 'object',
  title: 'HTTPValidationError',
} as const;

export const HealthCheckSchema = {
  properties: {
    healthy: {
      type: 'boolean',
      title: 'Healthy',
      description: 'Health status of the service',
    },
  },
  type: 'object',
  required: ['healthy'],
  title: 'HealthCheck',
  description: 'Response model to validate and return when performing a health check.',
} as const;

export const MunicipalitiesFilterSchema = {
  properties: {
    codes: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Codes',
      description: 'Filter by codes',
      examples: [[]],
    },
    feature_ids: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Feature Ids',
      description: 'Filter by feature IDs',
      examples: [[]],
    },
    name: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by name',
    },
  },
  type: 'object',
  title: 'MunicipalitiesFilter',
} as const;

export const MunicipalitiesSearchFilterRequestSchema = {
  properties: {
    geometry: {
      anyOf: [
        {
          $ref: '#/components/schemas/GeometryFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by geometry',
    },
    counties: {
      anyOf: [
        {
          $ref: '#/components/schemas/CountiesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by counties',
    },
    municipalities: {
      anyOf: [
        {
          $ref: '#/components/schemas/MunicipalitiesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by municipalities',
    },
  },
  type: 'object',
  title: 'MunicipalitiesSearchFilterRequest',
} as const;

export const MunicipalitiesSearchRequestSchema = {
  properties: {
    filters: {
      items: {
        $ref: '#/components/schemas/MunicipalitiesSearchFilterRequest',
      },
      type: 'array',
      title: 'Filters',
      description:
        'A list of filters to apply for searching municipalities, combined using OR logic.',
      default: [],
    },
  },
  type: 'object',
  title: 'MunicipalitiesSearchRequest',
} as const;

export const MunicipalitySchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the municipality',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the municipality',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Name of the municipality',
    },
    county: {
      $ref: '#/components/schemas/ShortCounty',
      description: 'County information the municipality belongs to',
    },
    area_ha: {
      type: 'number',
      title: 'Area Ha',
      description: 'Area of the municipality in hectares',
    },
    created_at: {
      type: 'string',
      format: 'date',
      title: 'Created At',
      description: 'Date of creation of the municipality',
    },
  },
  type: 'object',
  required: ['code', 'feature_id', 'name', 'county', 'area_ha', 'created_at'],
  title: 'Municipality',
} as const;

export const MunicipalityWithGeometrySchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the municipality',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the municipality',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Name of the municipality',
    },
    county: {
      $ref: '#/components/schemas/ShortCounty',
      description: 'County information the municipality belongs to',
    },
    area_ha: {
      type: 'number',
      title: 'Area Ha',
      description: 'Area of the municipality in hectares',
    },
    created_at: {
      type: 'string',
      format: 'date',
      title: 'Created At',
      description: 'Date of creation of the municipality',
    },
    geometry: {
      $ref: '#/components/schemas/Geometry',
      description: 'Geometry information of the municipality',
    },
  },
  type: 'object',
  required: ['code', 'feature_id', 'name', 'county', 'area_ha', 'created_at', 'geometry'],
  title: 'MunicipalityWithGeometry',
} as const;

export const NumberFilterSchema = {
  properties: {
    eq: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Eq',
      description: 'Filter by equal number',
    },
    gt: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Gt',
      description: 'Filter by greater than number',
    },
    gte: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Gte',
      description: 'Filter by greater than or equal number',
    },
    lt: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Lt',
      description: 'Filter by less than number',
    },
    lte: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Lte',
      description: 'Filter by not equal number',
    },
  },
  type: 'object',
  title: 'NumberFilter',
} as const;

export const ParcelSchema = {
  properties: {
    unique_number: {
      type: 'integer',
      title: 'Unique Number',
      description: 'Unique number of the parcel',
    },
    cadastral_number: {
      type: 'string',
      title: 'Cadastral Number',
      description: 'Cadastral number of the parcel',
    },
    updated_at: {
      type: 'string',
      format: 'date',
      title: 'Updated At',
      description: 'Date of update of the parcel',
    },
    area_ha: {
      type: 'number',
      title: 'Area Ha',
      description: 'Area of the parcel in hectares',
    },
    geometry: {
      $ref: '#/components/schemas/Geometry',
      description: 'Polygon geometry of the parcel',
    },
    status: {
      anyOf: [
        {
          $ref: '#/components/schemas/Status',
        },
        {
          type: 'null',
        },
      ],
      description: 'Status of the parcel',
    },
    purpose: {
      $ref: '#/components/schemas/Purpose',
      description: 'Purpose of the parcel',
    },
    municipality: {
      $ref: '#/components/schemas/ShortMunicipality',
      description: 'Municipality information the parcel belongs to',
    },
  },
  type: 'object',
  required: [
    'unique_number',
    'cadastral_number',
    'updated_at',
    'area_ha',
    'geometry',
    'status',
    'purpose',
    'municipality',
  ],
  title: 'Parcel',
} as const;

export const ParcelSearchFilterRequestSchema = {
  properties: {
    statuses: {
      anyOf: [
        {
          $ref: '#/components/schemas/StatusTypesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by statuses',
    },
    purpose_groups: {
      anyOf: [
        {
          $ref: '#/components/schemas/PurposeGroupFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by purpose groups',
    },
    purposes: {
      anyOf: [
        {
          $ref: '#/components/schemas/PurposeTypeFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by purposes',
    },
    geometry: {
      anyOf: [
        {
          $ref: '#/components/schemas/GeometryFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by geometry',
    },
    counties: {
      anyOf: [
        {
          $ref: '#/components/schemas/CountiesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by counties',
    },
    municipalities: {
      anyOf: [
        {
          $ref: '#/components/schemas/MunicipalitiesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by municipalities',
    },
    parcels: {
      anyOf: [
        {
          $ref: '#/components/schemas/ParcelsFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by parcels',
    },
  },
  type: 'object',
  title: 'ParcelSearchFilterRequest',
} as const;

export const ParcelsFilterSchema = {
  properties: {
    unique_numbers: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Unique Numbers',
      description: 'Filter by unique numbers',
      examples: [[]],
    },
    unique_number: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by unique number',
    },
    cadastral_number: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by cadastral number',
    },
    area_ha: {
      anyOf: [
        {
          $ref: '#/components/schemas/NumberFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by area',
    },
  },
  type: 'object',
  title: 'ParcelsFilter',
} as const;

export const ParcelsSearchRequestSchema = {
  properties: {
    filters: {
      items: {
        $ref: '#/components/schemas/ParcelSearchFilterRequest',
      },
      type: 'array',
      title: 'Filters',
      description: 'A list of filters to apply for searching parcels, combined using OR logic.',
      default: [],
    },
  },
  type: 'object',
  title: 'ParcelsSearchRequest',
} as const;

export const ParcelsSearchSortBySchema = {
  type: 'string',
  enum: ['unique_number', 'cadastral_number', 'updated_at', 'area_ha'],
  title: 'ParcelsSearchSortBy',
} as const;

export const PurposeSchema = {
  properties: {
    purpose_id: {
      type: 'integer',
      title: 'Purpose Id',
      description: 'Purpose ID',
    },
    purpose_group: {
      anyOf: [
        {
          $ref: '#/components/schemas/PurposeGroup',
        },
        {
          type: 'null',
        },
      ],
      description: 'Purpose group',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Purpose name',
    },
    full_name: {
      type: 'string',
      title: 'Full Name',
      description: 'Purpose full name',
    },
    full_name_en: {
      type: 'string',
      title: 'Full Name En',
      description: 'Purpose full name in english',
    },
  },
  type: 'object',
  required: ['purpose_id', 'purpose_group', 'name', 'full_name', 'full_name_en'],
  title: 'Purpose',
} as const;

export const PurposeGroupSchema = {
  properties: {
    group_id: {
      type: 'integer',
      title: 'Group Id',
      description: 'Purpose group ID',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Purpose group name',
    },
    full_name: {
      type: 'string',
      title: 'Full Name',
      description: 'Purpose group full name',
    },
  },
  type: 'object',
  required: ['group_id', 'name', 'full_name'],
  title: 'PurposeGroup',
} as const;

export const PurposeGroupFilterSchema = {
  properties: {
    group_ids: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Group Ids',
      description: 'Filter by purpose group IDs',
    },
    name: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by name',
    },
    full_name: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by full name',
    },
  },
  type: 'object',
  title: 'PurposeGroupFilter',
} as const;

export const PurposeTypeFilterSchema = {
  properties: {
    purpose_ids: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Purpose Ids',
      description: 'Filter by purpose IDs',
    },
    name: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by name',
    },
    full_name: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by full name',
    },
    full_name_en: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by full name in english',
    },
  },
  type: 'object',
  title: 'PurposeTypeFilter',
} as const;

export const ResidentialAreaSchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the residential area',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the residential area',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Name of the residential area',
    },
    municipality: {
      $ref: '#/components/schemas/ShortMunicipality',
      description: 'Municipality information the residential area belongs to',
    },
    area_ha: {
      type: 'number',
      title: 'Area Ha',
      description: 'Area of the residential area in hectares',
    },
    created_at: {
      type: 'string',
      format: 'date',
      title: 'Created At',
      description: 'Date of creation of the residential area',
    },
  },
  type: 'object',
  required: ['code', 'feature_id', 'name', 'municipality', 'area_ha', 'created_at'],
  title: 'ResidentialArea',
} as const;

export const ResidentialAreaWithGeometrySchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the residential area',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the residential area',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Name of the residential area',
    },
    municipality: {
      $ref: '#/components/schemas/ShortMunicipality',
      description: 'Municipality information the residential area belongs to',
    },
    area_ha: {
      type: 'number',
      title: 'Area Ha',
      description: 'Area of the residential area in hectares',
    },
    created_at: {
      type: 'string',
      format: 'date',
      title: 'Created At',
      description: 'Date of creation of the residential area',
    },
    geometry: {
      $ref: '#/components/schemas/Geometry',
      description: 'Geometry information of the residential area',
    },
  },
  type: 'object',
  required: ['code', 'feature_id', 'name', 'municipality', 'area_ha', 'created_at', 'geometry'],
  title: 'ResidentialAreaWithGeometry',
} as const;

export const ResidentialAreasFilterSchema = {
  properties: {
    codes: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Codes',
      description: 'Filter by codes',
      examples: [[]],
    },
    feature_ids: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Feature Ids',
      description: 'Filter by feature IDs',
      examples: [[]],
    },
    name: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by name',
    },
  },
  type: 'object',
  title: 'ResidentialAreasFilter',
} as const;

export const ResidentialAreasSearchFilterRequestSchema = {
  properties: {
    geometry: {
      anyOf: [
        {
          $ref: '#/components/schemas/GeometryFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by geometry',
    },
    counties: {
      anyOf: [
        {
          $ref: '#/components/schemas/CountiesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by counties',
    },
    municipalities: {
      anyOf: [
        {
          $ref: '#/components/schemas/MunicipalitiesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by municipalities',
    },
    residential_areas: {
      anyOf: [
        {
          $ref: '#/components/schemas/ResidentialAreasFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by residential areas',
    },
  },
  type: 'object',
  title: 'ResidentialAreasSearchFilterRequest',
} as const;

export const ResidentialAreasSearchRequestSchema = {
  properties: {
    filters: {
      items: {
        $ref: '#/components/schemas/ResidentialAreasSearchFilterRequest',
      },
      type: 'array',
      title: 'Filters',
      description:
        'A list of filters to apply for searching residential areas, combined using OR logic.',
      default: [],
    },
  },
  type: 'object',
  title: 'ResidentialAreasSearchRequest',
} as const;

export const RoomSchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the room',
    },
    room_number: {
      type: 'string',
      title: 'Room Number',
      description: 'Room number in the building or building section',
    },
    created_at: {
      type: 'string',
      format: 'date',
      title: 'Created At',
      description: 'Date of creation of the room address',
    },
    geometry: {
      $ref: '#/components/schemas/Geometry',
      description: 'Point geometry of the address',
    },
    address: {
      $ref: '#/components/schemas/ShortAddress',
      description: 'Address of the room',
    },
  },
  type: 'object',
  required: ['code', 'room_number', 'created_at', 'geometry', 'address'],
  title: 'Room',
} as const;

export const RoomsFilterSchema = {
  properties: {
    codes: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Codes',
      description: 'Filter by codes',
      examples: [[]],
    },
    room_number: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by room number',
    },
  },
  type: 'object',
  title: 'RoomsFilter',
} as const;

export const RoomsSearchFilterRequestSchema = {
  properties: {
    geometry: {
      anyOf: [
        {
          $ref: '#/components/schemas/GeometryFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by geometry',
    },
    counties: {
      anyOf: [
        {
          $ref: '#/components/schemas/CountiesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by counties',
    },
    municipalities: {
      anyOf: [
        {
          $ref: '#/components/schemas/MunicipalitiesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by municipalities',
    },
    residential_areas: {
      anyOf: [
        {
          $ref: '#/components/schemas/ResidentialAreasFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by residential areas',
    },
    streets: {
      anyOf: [
        {
          $ref: '#/components/schemas/StreetsFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by streets',
    },
    addresses: {
      anyOf: [
        {
          $ref: '#/components/schemas/AddressesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by addresses',
    },
    rooms: {
      anyOf: [
        {
          $ref: '#/components/schemas/RoomsFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by rooms',
    },
  },
  type: 'object',
  title: 'RoomsSearchFilterRequest',
} as const;

export const RoomsSearchRequestSchema = {
  properties: {
    filters: {
      items: {
        $ref: '#/components/schemas/RoomsSearchFilterRequest',
      },
      type: 'array',
      title: 'Filters',
      description: 'A list of filters to apply for searching rooms, combined using OR logic.',
      default: [],
    },
  },
  type: 'object',
  title: 'RoomsSearchRequest',
} as const;

export const RoomsSearchSortBySchema = {
  type: 'string',
  enum: ['code', 'room_number', 'created_at'],
  title: 'RoomsSearchSortBy',
} as const;

export const SearchSortBySchema = {
  type: 'string',
  enum: ['code', 'name', 'feature_id', 'created_at'],
  title: 'SearchSortBy',
} as const;

export const SearchSortOrderSchema = {
  type: 'string',
  enum: ['asc', 'desc'],
  title: 'SearchSortOrder',
} as const;

export const ShortAddressSchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the address',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the address',
    },
    plot_or_building_number: {
      type: 'string',
      title: 'Plot Or Building Number',
      description: 'Plot or building number of the address',
    },
    building_block_number: {
      anyOf: [
        {
          type: 'string',
          minLength: 1,
        },
        {
          type: 'null',
        },
      ],
      title: 'Building Block Number',
      description: 'Plot or building number of the address',
    },
    postal_code: {
      type: 'string',
      title: 'Postal Code',
      description: 'Postal code of the address',
    },
    street: {
      anyOf: [
        {
          $ref: '#/components/schemas/FlatStreet',
        },
        {
          type: 'null',
        },
      ],
      description: 'Street information the address belongs to',
    },
    residential_area: {
      anyOf: [
        {
          $ref: '#/components/schemas/FlatResidentialArea',
        },
        {
          type: 'null',
        },
      ],
      description: 'Residential area information the address belongs to',
    },
    municipality: {
      $ref: '#/components/schemas/ShortMunicipality',
      description: 'Municipality information the address belongs to',
    },
  },
  type: 'object',
  required: [
    'code',
    'feature_id',
    'plot_or_building_number',
    'building_block_number',
    'postal_code',
    'street',
    'residential_area',
    'municipality',
  ],
  title: 'ShortAddress',
} as const;

export const ShortCountySchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the county',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the county',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Name of the county',
    },
  },
  type: 'object',
  required: ['code', 'feature_id', 'name'],
  title: 'ShortCounty',
} as const;

export const ShortMunicipalitySchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the municipality',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the municipality',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Name of the municipality',
    },
    county: {
      $ref: '#/components/schemas/ShortCounty',
      description: 'County information the municipality belongs to',
    },
  },
  type: 'object',
  required: ['code', 'feature_id', 'name', 'county'],
  title: 'ShortMunicipality',
} as const;

export const ShortResidentialAreaSchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the residential area',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the residential area',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Name of the residential area',
    },
    municipality: {
      $ref: '#/components/schemas/ShortMunicipality',
      description: 'Municipality information the residential area belongs to',
    },
  },
  type: 'object',
  required: ['code', 'feature_id', 'name', 'municipality'],
  title: 'ShortResidentialArea',
} as const;

export const StatusSchema = {
  properties: {
    status_id: {
      type: 'integer',
      title: 'Status Id',
      description: 'Status ID',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Status name',
    },
    name_en: {
      type: 'string',
      title: 'Name En',
      description: 'Status name in english',
    },
    full_name: {
      type: 'string',
      title: 'Full Name',
      description: 'Status full name',
    },
    full_name_en: {
      type: 'string',
      title: 'Full Name En',
      description: 'Status full name in english',
    },
  },
  type: 'object',
  required: ['status_id', 'name', 'name_en', 'full_name', 'full_name_en'],
  title: 'Status',
} as const;

export const StatusTypesFilterSchema = {
  properties: {
    status_ids: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Status Ids',
      description: 'Filter by status IDs',
    },
    name: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by name',
    },
    name_en: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by name in english',
    },
    full_name: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by full name',
    },
    full_name_en: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by full name in english',
    },
  },
  type: 'object',
  title: 'StatusTypesFilter',
} as const;

export const StreetSchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the street',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the street',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Name of the street',
    },
    full_name: {
      type: 'string',
      title: 'Full Name',
      description: 'The full name of the street, including its type',
    },
    length_m: {
      type: 'number',
      title: 'Length M',
      description: 'The total length of the street in meters',
    },
    created_at: {
      type: 'string',
      format: 'date',
      title: 'Created At',
      description: 'Date of creation of the street',
    },
    residential_area: {
      $ref: '#/components/schemas/ShortResidentialArea',
      description: 'Residential area information the street belongs to',
    },
  },
  type: 'object',
  required: [
    'code',
    'feature_id',
    'name',
    'full_name',
    'length_m',
    'created_at',
    'residential_area',
  ],
  title: 'Street',
} as const;

export const StreetWithGeometrySchema = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
      description: 'Unique code of the street',
    },
    feature_id: {
      type: 'integer',
      title: 'Feature Id',
      description: 'Feature ID of the street',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'Name of the street',
    },
    full_name: {
      type: 'string',
      title: 'Full Name',
      description: 'The full name of the street, including its type',
    },
    length_m: {
      type: 'number',
      title: 'Length M',
      description: 'The total length of the street in meters',
    },
    created_at: {
      type: 'string',
      format: 'date',
      title: 'Created At',
      description: 'Date of creation of the street',
    },
    residential_area: {
      $ref: '#/components/schemas/ShortResidentialArea',
      description: 'Residential area information the street belongs to',
    },
    geometry: {
      $ref: '#/components/schemas/Geometry',
      description: 'Line geometry information of the street',
    },
  },
  type: 'object',
  required: [
    'code',
    'feature_id',
    'name',
    'full_name',
    'length_m',
    'created_at',
    'residential_area',
    'geometry',
  ],
  title: 'StreetWithGeometry',
} as const;

export const StreetsFilterSchema = {
  properties: {
    codes: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Codes',
      description: 'Filter by codes',
      examples: [[]],
    },
    feature_ids: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Feature Ids',
      description: 'Filter by feature IDs',
      examples: [[]],
    },
    name: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by name',
    },
    full_name: {
      anyOf: [
        {
          $ref: '#/components/schemas/StringFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by full name',
    },
  },
  type: 'object',
  title: 'StreetsFilter',
} as const;

export const StreetsSearchFilterRequestSchema = {
  properties: {
    geometry: {
      anyOf: [
        {
          $ref: '#/components/schemas/GeometryFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by geometry',
    },
    counties: {
      anyOf: [
        {
          $ref: '#/components/schemas/CountiesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by counties',
    },
    municipalities: {
      anyOf: [
        {
          $ref: '#/components/schemas/MunicipalitiesFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by municipalities',
    },
    residential_areas: {
      anyOf: [
        {
          $ref: '#/components/schemas/ResidentialAreasFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by residential areas',
    },
    streets: {
      anyOf: [
        {
          $ref: '#/components/schemas/StreetsFilter',
        },
        {
          type: 'null',
        },
      ],
      description: 'Filter by streets',
    },
  },
  type: 'object',
  title: 'StreetsSearchFilterRequest',
} as const;

export const StreetsSearchRequestSchema = {
  properties: {
    filters: {
      items: {
        $ref: '#/components/schemas/StreetsSearchFilterRequest',
      },
      type: 'array',
      title: 'Filters',
      description: 'A list of filters to apply for searching streets, combined using OR logic.',
      default: [],
    },
  },
  type: 'object',
  title: 'StreetsSearchRequest',
} as const;

export const StringFilterSchema = {
  properties: {
    contains: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Contains',
      description: 'Filter by containing a string (case insensitive)',
      examples: [''],
    },
    exact: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Exact',
      description: 'Filter by exact string (case insensitive)',
      examples: [''],
    },
    starts: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Starts',
      description: 'Filter by starting with a string (case insensitive)',
      examples: [''],
    },
  },
  type: 'object',
  title: 'StringFilter',
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string',
          },
          {
            type: 'integer',
          },
        ],
      },
      type: 'array',
      title: 'Location',
    },
    msg: {
      type: 'string',
      title: 'Message',
    },
    type: {
      type: 'string',
      title: 'Error Type',
    },
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError',
} as const;
